config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about" => "pages#about"
  get "admin" => "pages#admin"
  get "contact" => "pages#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def About
  end

  def Admin
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Everbudcast</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
      <li><%= link_to "Admin", admin_path %></li> 
      <li><%= link_to "Contact", contact_path %></li> 
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budcast</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <!-- Bootstrap -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Everbudcast</h1>
<p1>Our project and how we decided to bring to life this idea</p1>

<div class="banner">

      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <img src="/assets/beach.jpg" alt="Going to the beach">
            <div class="carousel-caption">
              <h2>HTML is my Beach House</h2>
            </div>
          </div>
          <div class="item">
            <img src="/assets/birds.jpg" alt="CSS Birds on a Wall">
            <div class="carousel-caption">
              <h2>CSS is where I meet my Friends</h2>
            </div>
          </div>
          <div class="item">
            <img src="/assets/tea.jpg" alt="">
            <div class="carousel-caption">
                <h2>JavaScript is my Hot Hot Tea</h2>
            </div>
          </div>
        </div><!-- .carousel-inner --> 

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div><!-- .carousel --> 
    </div><!-- .banner --> 

    


    <div class="container marketing">
   
      <!-- START THE FEATURETTES -->
      <hr class="divider">

  
      <div class="row">
        <div class="col-md-7">
          <h2 class="featurette-heading">HTML is <span class="text-muted">100% Free</span></h2>

          <p class="lead">No gimmicks. No bull. HTML is brought to you for free by the W3C. It can be used from the comfort of your own home. And it works in the browser along with CSS and JavaScript. Use all three to make a kickass Website.</p>

        </div>
        <div class="col-md-5">
           <img src="/assets/dog.jpg" alt="Dogs love HTML" class="img-thumbnail">
        </div>
      </div>

      <hr class="divider">

      <div class="row">
        <div class="col-md-5">
          <img src="/assets/chrome.jpg" alt="Chrome Browser">
        </div>
        <div class="col-md-7">

          <h2 class="featurette-heading">What's Included with HTML?</h2>
          <p class="lead">Tags to make words <strong>bold</strong>. <em>Like a boss</em> And tons of CSS properties to style your page: <code> .ninja { color: black; visibility: none; }</code></p>

        </div>
      </div>

      <hr class="divider">

      <div class="companies">
        <div class="text-center">
          <h3 class="text-muted">HTML is Trusted By 100,000+ Companies Including</h3>
        </div>
        <div class="row">
          <div class="col-md-3">
              <img src="/assets/company1.svg" alt="Bloomberg">        
          </div>
          <div class="col-md-3">
              <img src="/assets/company2.svg" alt="Google">        
         </div>
         <div class="col-md-3">
             <img src="/assets/company3.svg" alt="Y Combinator">        
         </div>
           <div class="col-md-3">
              <img src="/assets/company4.svg" alt="Singularity University">        
          </div>
        </div>
      </div><!-- .trusted-companies --> 


   </div><!-- /.container --> 

      

    <!-- FOOTER -->
    <footer>
      <p class="pull-right"><a href="#">Back to top</a></p>
      <p>Made with <a href="http://www.onemonthtml.com" target="_blank">One Month HTML</a></p>
    </footer>



    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.js"></script>
  </body>
</html>

app/views/pages/admin.html.erb
<h1>Admin Budcast - Jorn & Daniel administrators </h1>
<p1> Here we will manage the whole project behind the scenes</p1>

app/views/pages/contact.html.erb
<h1> Contact Everbudcast</h1>
<p1> our info </p1>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>We are preparing the field for next generation Finance Solution!</h1>
	Click here to <%= link_to "Sign Up", "#", class: "btn btn-success btn-lg"  %>
</div>

<div class="banner">

      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <img src="/assets/beach.jpg" alt="Going to the beach">
            <div class="carousel-caption">
              <h2>HTML is my Beach House</h2>
            </div>
          </div>
          <div class="item">
            <img src="/assets/birds.jpg" alt="CSS Birds on a Wall">
            <div class="carousel-caption">
              <h2>CSS is where I meet my Friends</h2>
            </div>
          </div>
          <div class="item">
            <img src="/assets/tea.jpg" alt="">
            <div class="carousel-caption">
                <h2>JavaScript is my Hot Hot Tea</h2>
            </div>
          </div>
        </div><!-- .carousel-inner --> 

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div><!-- .carousel --> 
    </div><!-- .banner --> 

    


    <div class="container marketing">
   
      <!-- START THE FEATURETTES -->
      <hr class="divider">

  
      <div class="row">
        <div class="col-md-7">
          <h2 class="featurette-heading">HTML is <span class="text-muted">100% Free</span></h2>

          <p class="lead">No gimmicks. No bull. HTML is brought to you for free by the W3C. It can be used from the comfort of your own home. And it works in the browser along with CSS and JavaScript. Use all three to make a kickass Website.</p>

        </div>
        <div class="col-md-5">
           <img src="/assets/dog.jpg" alt="Dogs love HTML" class="img-thumbnail">
        </div>
      </div>

      <hr class="divider">

      <div class="row">
        <div class="col-md-5">
          <img src="/assets/chrome.jpg" alt="Chrome Browser">
        </div>
        <div class="col-md-7">

          <h2 class="featurette-heading">What's Included with HTML?</h2>
          <p class="lead">Tags to make words <strong>bold</strong>. <em>Like a boss</em> And tons of CSS properties to style your page: <code> .ninja { color: black; visibility: none; }</code></p>

        </div>
      </div>

      <hr class="divider">

      <div class="companies">
        <div class="text-center">
          <h3 class="text-muted">HTML is Trusted By 100,000+ Companies Including</h3>
        </div>
        <div class="row">
          <div class="col-md-3">
              <img src="/assets/company1.svg" alt="Bloomberg">        
          </div>
          <div class="col-md-3">
              <img src="/assets/company2.svg" alt="Google">        
         </div>
         <div class="col-md-3">
             <img src="/assets/company3.svg" alt="Y Combinator">        
         </div>
           <div class="col-md-3">
              <img src="/assets/company4.svg" alt="Singularity University">        
          </div>
        </div>
      </div><!-- .trusted-companies --> 


   </div><!-- /.container --> 

      

    <!-- FOOTER -->
    <footer>
      <p class="pull-right"><a href="#">Back to top</a></p>
      <p>Made with <a href="http://www.onemonthtml.com" target="_blank">One Month HTML</a></p>
    </footer>



    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.js"></script>
  </body>
</html>